### PR TITLE
Package snooper patch

### PR DESCRIPTION
**Pull request by aminya**
Ready to get merged
- Renaming
- Backward compatibility: https://github.com/timholy/SnoopCompile.jl/pull/66/files#diff-59e7d35dcb5b9ea6812f69c4be9a05d3R33

### CODE REVIEW

**Comment by aminya** [comment]
I get undef var error for macros. It seems they are different than functions
```julia
const snoopiBot = snoopi_bot
const snoopiBench = snoopi_bench
```

**Comment by aminya** [comment]
This is ready to get merged. It deprecates old macros and uses the new name.

**Comment by aminya** [comment]
@timholy could you merge this and register a new release

**Comment by timholy** [comment]
Thanks, sorry for the delay!

**Pull request merged**
