### PR TITLE
Tweak `anonrex`

### PR DESCRIPTION
**Pull request by timholy**
Should also get the tests passing on Travis

### CODE REVIEW

**Comment by yhls** [comment]
Did we want to exclude anonymous functions of the form `##something#123`?

**Comment by timholy** [comment]
I'm torn. Generators like `##s27#8` are reproducible until the code changes, maybe it doesn't hurt to keep them?

**Comment by yhls** [comment]
I think they're not reproducible across different versions of Julia, but I guess #30 makes them harmless.

**Comment by timholy** [comment]
There will be a different precompile cache anyway for different versions.

I think I'll go with this and we can consider pruning more methods later.

**Pull request merged**
