### PR TITLE
Version 1.5

### PR DESCRIPTION
**Pull request by timholy**
Submitted as a PR just to make sure all the CI works properly.

### CODE REVIEW

**Comment by aminya** [comment]
It would be nice if we merge #87 before registration.

**Comment by timholy** [comment]
Agreed, let's wait for it.

**Comment by timholy** [comment]
Looks like there's a path issue on Windows, though (`\\` vs `/`).

**Comment by aminya** [comment]
Oh! I added that test recently. Let me apply some GoodPath on it.

**Comment by timholy** [comment]
Assuming this passes, do you approve?

**Comment by timholy** [comment]
Looks like there's still
```
pathof_noload: Test Failed at D:\a\SnoopCompile.jl\SnoopCompile.jl\test\bot\botutils.jl:5
  Expression: p == pnl
   Evaluated: "C:\\Users\\runneradmin\\.julia\\packages\\MatLang\\TbsCI\\src\\MatLang.jl" == "C:/Users/runneradmin/.julia/packages/MatLang/TbsCI/src/MatLang.jl"
Stacktrace:
 [1] top-level scope at D:\a\SnoopCompile.jl\SnoopCompile.jl\test\bot\botutils.jl:5
 [2] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Test\src\Test.jl:1113
 [3] top-level scope at D:\a\SnoopCompile.jl\SnoopCompile.jl\test\bot\botutils.jl:2
```
Is this likely outdated? I am not certain that closing and reopening reruns all tests.

**Comment by timholy** [comment]
Ah, I found a "rerun all jobs button, let's see what happens."

**Comment by aminya** [comment]
Did you merge master into this branch?

**Comment by timholy** [comment]
Oh, I see, the failures were specifically for `push` and not `pull_request`. Yes, I bet it's fixed.

**Pull request merged**
