### PR TITLE
missing includer issue

### PR DESCRIPTION
**Pull request by aminya**
To fix missing includer issue in https://github.com/JuliaPlots/Plots.jl/issues/2838

⚠️ emergency patch 

- Adds gitattributes to prevent line ending changing during uploads from different operating systems
- removes previous bash script that did a similar thing
- throws an error for anyone who uses the bash script (there is no other way to let them know 😞)

Let's merge this before people run into the same issue.

### CODE REVIEW

**Comment by aminya** [comment]
Plots test pass locally! I wonder why it is not added to the pull request that the bot makes.

@timholy "Lost of methods" tests fail in the nightly. Has anything changed in nightly?

**Comment by aminya** [comment]
I wonder if https://github.com/timholy/SnoopCompile.jl/pull/122/commits/f50b27a059af56bc910038779900d4b18e431833 actually fix the issue. 😞 This is a patch that we cannot send to our users unless we  find all the repositories that use SnoopCompile.yml

We should take #99 serious now. 🤦‍♂️

**Comment by aminya** [comment]
@timholy Let's merge this before people run into the same issue. Having a pull request polluted with whitespace changes is better than not having the includer file. This is mostly a doc update now.

**Comment by aminya** [comment]
@timholy Could you take a look at this?

**Comment by timholy** [comment]
Hmm, messing with a repo's git attributes seems beyond the scope of SnoopCompile, and it seems like material better placed in PkgTemplates than here. Is there a more minimal fix possible?

**Comment by aminya** [comment]
> Hmm, messing with a repo's git attributes seems beyond the scope of SnoopCompile, and it seems like material better placed in PkgTemplates than here. Is there a more minimal fix possible?

Yes, it should be in PkgTemplates too, but specifically for this case, we might need some sort of managing this. One way, I can think of is to have a `SnoopCompileBot.post_generation` function that runs in the Create_PR step, and we can do some stuff in it (fixing line-ending issues) or some compatibility things that may arise later.

**Comment by timholy** [comment]
I'd like this to be as small a fix as possible for this bug, and then let's split the bot out into a separate package and you can do more heroic repo-surgery there.

**Comment by timholy** [comment]
Or alternatively, if it really is hard to fix this without something big (notifying all existing users, whatever), then let's just do the split now and you can fix in 2.0?

**Comment by aminya** [comment]
As I said already, I am OK with splitting the bot into a separate repository. We can do it at any time.

For later fixes, I want to add that `post_generation` function to refactor the Create_PR step in `SnoopCompile.yml`.

Currently, I have to error to inform the users about the faulty bash script. That only affects the users of multios/multiversion configuration.

**Comment by timholy** [comment]
As mentioned above, I don't plan to merge this before we switch to 2.0. Changing the git settings on the repo by default is beyond the scope of this package. I recommend creating the new bot repo package soon.

**Pull request closed without merging**
