### PR TITLE
Handle # characters in function-types (julia 0.5). Fixes #7

### LINKED ISSUE #7: Not Very useful on 0.5
0.5 signatures contain a lot of calls with `#` in them, which SnoopCompile ignores.

### PR DESCRIPTION
**Pull request by timholy**
Replaces `Base.#any` with `typeof(Base.any)`.

### CODE REVIEW

**Comment by timholy** [comment]
CC @Keno.

**Comment by timholy** [comment]
Let me know if this works.

**Comment by Keno** [comment]
I think you'll still run into trouble with anonymous functions which are `#42` or so.

**Comment by timholy** [comment]
Now you're being greedy. I doubt there's any way around that problem; even if you extracted the AST associated with that function, constructed a new anonymous function that does the same thing, and issued a precompile directive, it wouldn't help because the name in a new session wouldn't match.

**Comment by Keno** [comment]
I'm not saying it should work for anonymous functions, I'm saying this approach will produce invalid output on them.

**Comment by timholy** [comment]
Ah, got it. Thanks for pointing that out, and already fixed (hopefully). Of course one can edit the resulting file manually, but you're right that there's no good reason not to exclude those automatically.

Feel free to give this a whirl and let me know if you have problems.

**Pull request merged**
