### PR TITLE
Adding a full real-world example

### PR DESCRIPTION
**Pull request by aminya**
@timholy If you like, you can merge this for a full real-world example for using SnoopCompile

### CODE REVIEW

**Comment by timholy** [comment]
This is reasonable, but perhaps we should allow multiple packages. (This is not the first real-world user of SnoopCompile.) Can you maybe set it up so that it's a list, with MatLang currently the only entry in the list?

**Comment by aminya** [comment]
@timholy That's a good idea. Done!

**Comment by timholy** [comment]
Thanks!

**Comment by timholy** [comment]
Sorry to have also shaken things up rather a lot since you last looked at this package!

**Pull request merged**
